services:
  ui:
    build:
      context: ..
      dockerfile: reso-web-client/Dockerfile
      target: build
    ports:
      - "5173:80"
    command: ["npx", "vite", "--config", "vite.config.docker.ts"]
    volumes:
      - ../reso-web-client/src:/app/src
      - ../reso-web-client/index.html:/app/index.html
      - ../reso-web-client/vite.config.docker.ts:/app/vite.config.docker.ts
    environment:
      NODE_ENV: development
